---
name: Release Version

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  release:
    name: "Release to GitHub"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Semantic Release and Plugins
        run: | # yamllint disable-line rule:line-length
          mkdir -p /tmp/semantic-release
          cd /tmp/semantic-release && npm install --legacy-peer-deps semantic-release@22.0.12 conventional-changelog-conventionalcommits@6

      - name: Release Version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
        run: /tmp/semantic-release/node_modules/.bin/semantic-release
